### ISSUE TITLE
Tooltip weird behavior

### ISSUE THREAD

**Issue by brunocalado** [richardgaywood/foundry-penllawen-compendium-table-maker#10]
Hi.

When you trigger the tooltip you get stuck with it. Is it possible to make the tooltip less invasive?
https://user-images.githubusercontent.com/4999783/228011203-2380a24f-1584-41a8-bd8f-a4ca9b9d4e5c.mp4

tks, great improvement

**Comment by richardgaywood** [comment]
I think this got solved in the last release by tweaking the tooltip appear/disappear timing. Plz reopen if you're still seeing this behaviour.
