### ISSUE TITLE
Add support for Abilities

### ISSUE THREAD

**Issue by loofou** [richardgaywood/foundry-penllawen-compendium-table-maker#3]
Hey,

Great module, I am using it a lot at the moment to build an easier way for my players to find which edges, hindrances, etc are available in our setting.

One thing I noticed is that right now there is no support for Abilities. As races/species and archetypes are handled as abilities, this means we can't create nice tables of available races or archetypes. Rifts has quite a bunch of them for example.

Would you be able to add support for abilities (or alternatively allow us to use our own templates somehow?)

Thanks!
Loofou

**Comment by richardgaywood** [comment]
Hi! Thanks for your kind words!

Adding abilities is pretty easy; I'm happy to take that as a request for the (near) future. 

If you're feeling excitable and impatient, you're welcome to have a go -- I can provide some guidance here or on Discord. But don't feel you have to, I'm happy to do it.

**Comment by richardgaywood** [comment]
No worries. I've done most of it now, need to solve a translation issue then it should be good to ship.

**Comment by richardgaywood** [comment]
Fixed in v1.3.0
