### ISSUE TITLE
Some don't get a title

### ISSUE THREAD

**Issue by brunocalado** [richardgaywood/foundry-penllawen-compendium-table-maker#7]
Hi.

Some of the items don't receive the H3 tag and don't show up with a tiitle. I don't know if all should have the tille or none of them. Anyway, the search is useless. Can you add a way to prevent add the tag? tks 

![image](https://user-images.githubusercontent.com/4999783/226186621-bc37bbe0-9aff-443f-aecf-f96261890050.png)

**Comment by richardgaywood** [comment]
This is a known issue. The way I make the popover blocks isn't very robust. It's on my list but not a small/quick fix.

**Comment by richardgaywood** [comment]
This should now be fixed in v1.4.0, as I rewrote the hover popup code to use proper Foundry ones.
