### ISSUE TITLE
Rank Filter

### ISSUE THREAD

**Issue by brunocalado** [richardgaywood/foundry-penllawen-compendium-table-maker#8]
Hi.

Can you add a filter by Rank for powers/edges?

Read text can be a problem. Maybe, this feature would require the system to have a static field for requirement rank
![image](https://user-images.githubusercontent.com/4999783/226186930-9ad6fa47-2ac0-4ef2-a62d-8b3556bea682.png)

tks

**Comment by richardgaywood** [comment]
Very difficult to solve properly. There's no dedicated data structure for storing this in items, and parsing it out of the text will be vulnerable to typos, and wont work for powers where the rank requirement is not set or uses an abbreviation. It also won't work for non-English languages. Going to WONTFIX this one.
